FROM node:24-alpine AS build
WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm ci

COPY ./frontend ./
RUN npm run build

FROM nginx:1.29-alpine
RUN apk add --no-cache gettext
COPY ./frontend/nginx.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
ENV API_URL=http://api:8080
ENV API_HOST=api